/**
 * Maps a logical photo path (as it appears in src/data/** and the modal data)
 * to the size variant generated by scripts/gallery-assets.mjs.
 *
 *   photoSrc('/Events/ROBOKIDS2026/a.jfif', 'thumb') -> '/Events/ROBOKIDS2026/a-thumb.webp'
 *   photoSrc('/Events/ROBOKIDS2026/a.jfif')          -> '/Events/ROBOKIDS2026/a-main.webp'
 *   photoSrc('/Events/x/VID-a.mp4', 'poster')        -> '/Events/x/VID-a-poster.webp'
 *
 * Every call stays a plain string transform so data files can import and wrap
 * paths without runtime cost, and missing assets fall back through WebpImage's
 * once-only revert to the original source.
 */

const SIZES = {
  main: '-main.webp',
  thumb: '-thumb.webp',
  poster: '-poster.webp',
};

export function photoSrc(src, size = 'main') {
  if (typeof src !== 'string') return src;
  const suffix = SIZES[size];
  if (!suffix) return src;

  const raster = /\.(jpe?g|jfif|png)$/i;
  const video = /\.(mp4|webm)$/i;
  if (!raster.test(src) && !video.test(src)) return src;

  return src.replace(raster, '').replace(video, '') + suffix;
}

export default photoSrc;
