import { webpSrc } from '../lib/webp';
import { photoSrc } from '../lib/photoSrc';

/**
 * <img> that prefers the gallery-variant WebP generated by
 * `node scripts/gallery-assets.mjs` (-main.webp / -thumb.webp), falling back to
 * the single full WebP from `npm run images:convert`, then to the original
 * source once — so a not-yet-converted photo can never render broken.
 *
 * <picture> is made layout-neutral by `picture { display: contents }` in
 * utilities.css.
 */
export default function WebpImage({ src, onError, size, ...rest }) {
  // Explicit gallery-variant request (thumb/main) when one was generated.
  const variant = size === 'thumb' || size === 'main' ? photoSrc(src, size) : webpSrc(src);

  if (!variant) {
    return <img src={src} onError={onError} {...rest} />;
  }

  const handleError = (event) => {
    const img = event.currentTarget;
    if (img.dataset.webpFallback !== 'done') {
      img.dataset.webpFallback = 'done';
      // Try the legacy full WebP first, then the original.
      const legacy = webpSrc(src);
      if (legacy && img.src !== new URL(legacy, window.location.href).href) {
        img.src = legacy;
        return;
      }
      img.src = src;
      return;
    }
    onError?.(event);
  };

  return (
    <picture>
      <source srcSet={variant} type="image/webp" />
      <img src={src} onError={handleError} {...rest} />
    </picture>
  );
}
