import { webpSrc } from '../lib/webp';

/**
 * <img> that prefers the WebP sibling generated by `npm run images:convert`.
 * If the WebP is missing or fails to load, the element reverts to the
 * original source once, then runs the consumer's onError as usual — so a
 * not-yet-converted photo can never render broken.
 *
 * <picture> is made layout-neutral by `picture { display: contents }` in
 * utilities.css.
 */
export default function WebpImage({ src, onError, ...rest }) {
  const webp = webpSrc(src);

  if (!webp) {
    return <img src={src} onError={onError} {...rest} />;
  }

  const handleError = (event) => {
    const img = event.currentTarget;
    if (img.dataset.webpFallback !== 'done') {
      img.dataset.webpFallback = 'done';
      img.src = src;
      return;
    }
    onError?.(event);
  };

  return (
    <picture>
      <source srcSet={webp} type="image/webp" />
      <img src={src} onError={handleError} {...rest} />
    </picture>
  );
}
